LibDir=Libs/
CnDir=$(LibDir)ClientLibs/
all:
	g++ -pthread -o Client.out Client.cpp $(CnDir)httplib.h $(LibDir)HttpClientCorridor.h $(CnDir)ConnectConfig.cpp $(CnDir)ConsoleWork.cpp $(CnDir)GameMap.cpp
